name: my workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Execute tests
        run: exit 0
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: one
        run: |
          pwd
          mkdir -p one/two/tree

      - name: two
        run: |
          pwd
          cd one
          pwd
          
      - name: tree
        run: |
          pwd
          
      - name: four
        run: |
          pwd
                 
