name: my workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Execute tests
        run: exit 0
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy Non prod app
        if: github.ref == 'refs/heads/develop'
        run: |
          echo "This is develop branch"
          exit 0
      - name: Deploy Prodapp
        if: github.ref == 'refs/heads/prod'
        run: |
          echo "This is prod branch"
          exit 0
