# This is a basic workflow to help you get started with Actions

name: Deploy new changes

on:
  push:
    branches:
      - dev
      - test
      - demo
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:  
      - name: Extract branch name
        shell: bash
        run: |
            echo git_branch=`echo ${GITHUB_REF#refs/heads/}` >> $GITHUB_ENV
        id: extract_branch
  
      - name: Extract repository name
        shell: bash
        run: |
            echo git_repo=`echo ${GITHUB_REPOSITORY#*/}` >> $GITHUB_ENV
        id: extract_repo
  
      - name: Execute SSH commmands on remote server
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
          command: |
            echo branch is $git_branch
            echo repo is $git_repo
            ls -lah /opt/webapp
            cd /opt/webapp
            pwd
            ls -las /opt/webapp/${git_branch}.${git_repo}
            echo "I am $NAME"
