# This is a basic workflow to help you get started with Actions

name: Deploy new changes

on:
  push:
    branches:
      - dev
      - test
      - demo
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: ls -a via ssh
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: ls -a
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
          
      - name: Execute SSH commmands on remote server
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: ${{ secrets.USER_NAME }}@${{ secrets.HOST }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
          command: |
            ls -lah
            echo "I am $NAME"
