# This is a basic workflow to help you get started with Actions

name: Deploy new changes

on:
  push:
    branches:
      - dev
      - test
      - demo
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:  
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
  
      - name: Extract repository name
        shell: bash
        run: echo "##[set-output name=repo;]$(echo ${GITHUB_REPOSITORY#*/})"
        id: extract_repo
  
      - name: Execute SSH commmands on remote server
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
          command: |
            ls -lah /opt/webapp
            cd /opt/webapp
            pwd
            ls -las /opt/webapp/eng:${{ steps.extract_branch.outputs.branch }}.eng:${{ steps.extract_repo.outputs.repo }}
            echo "I am $NAME"
